name: Run Scraper_Schedule File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List files before running script
        run: |
          echo "Listing files before running the script"
          ls -la

      - name: Run scraping script
        run: |
          python NewSectorScanner.py

      - name: List files after running script
        run: |
          echo "Listing files after running the script"
          ls -la

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Updated logs"
          fi

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload csv files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-files
          path: "*.csv"  # Updated to target CSV files
